using System.Text;
using ExcelToGame.Models;
using ExcelToGame.Config;
using ExcelToGame.Utils;

namespace ExcelToGame.Core;

/// <summary>
/// C#代码生成模块 - 生成Unity使用的实体类
/// </summary>
public class CSharpCodeGenerator
{
    private readonly AppConfig _config;
    
    public CSharpCodeGenerator(AppConfig config)
    {
        _config = config;
    }
    
    /// <summary>
    /// 生成C#实体类
    /// </summary>
    public async Task<bool> GenerateClassAsync(TableData tableData)
    {
        try
        {
            var outputPath = Path.Combine(_config.GetFullCSharpPath(), $"{tableData.ClassName}.cs");
            var code = GenerateClassCode(tableData);
            
            await FileUtils.WriteTextAsync(outputPath, code);
            
            Logger.Success($"生成C#类: {outputPath}");
            return true;
        }
        catch (Exception ex)
        {
            Logger.Error($"生成C#类失败 [{tableData.ClassName}]: {ex.Message}");
            return false;
        }
    }
    
    /// <summary>
    /// 生成类代码
    /// </summary>
    private string GenerateClassCode(TableData tableData)
    {
        var sb = new StringBuilder();
        
        // 文件头
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("// 此文件由Excel转配置工具自动生成，请勿手动修改");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine();
        sb.AppendLine($"namespace {_config.CSharpNamespace};");
        sb.AppendLine();
        
        // 类注释
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// {tableData.FileName} 配置数据");
        sb.AppendLine("/// </summary>");
        
        // 类声明（支持继承）
        var inheritance = tableData.ParentTableName != null 
            ? $" : {tableData.ParentTableName}" 
            : "";
        sb.AppendLine($"[Serializable]");
        sb.AppendLine($"public class {tableData.ClassName}{inheritance}");
        sb.AppendLine("{");
        
        // 生成字段属性
        var dataFields = tableData.GetDataFields();
        foreach (var field in dataFields)
        {
            // 字段注释
            if (!string.IsNullOrEmpty(field.Comment))
            {
                sb.AppendLine("    /// <summary>");
                sb.AppendLine($"    /// {field.Comment}");
                sb.AppendLine("    /// </summary>");
            }
            
            // 特性标记
            if (field.IsPrimaryKey)
            {
                sb.AppendLine("    [UnityEngine.SerializeField]");
            }
            
            // 属性声明
            var typeName = field.GetCSharpType();
            sb.AppendLine($"    public {typeName} {field.Name};");
            sb.AppendLine();
        }
        
        // 生成默认构造函数
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// 默认构造函数");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine($"    public {tableData.ClassName}()");
        sb.AppendLine("    {");
        
        // 初始化数组和列表
        foreach (var field in dataFields.Where(f => f.IsArray))
        {
            sb.AppendLine($"        {field.Name} = new();");
        }
        
        sb.AppendLine("    }");
        sb.AppendLine();
        
        // 生成ToString方法
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// 返回对象的字符串表示");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public override string ToString()");
        sb.AppendLine("    {");
        sb.AppendLine($"        return $\"[{tableData.ClassName}]\";");
        sb.AppendLine("    }");
        
        sb.AppendLine("}");
        
        return sb.ToString();
    }
    
    /// <summary>
    /// 生成配置管理器类（可选）
    /// </summary>
    public async Task<bool> GenerateConfigManagerAsync(List<TableData> tables)
    {
        try
        {
            var outputPath = Path.Combine(_config.GetFullCSharpPath(), "ConfigManager.cs");
            var code = GenerateConfigManagerCode(tables);
            
            await FileUtils.WriteTextAsync(outputPath, code);
            
            Logger.Success($"生成配置管理器: {outputPath}");
            return true;
        }
        catch (Exception ex)
        {
            Logger.Error($"生成配置管理器失败: {ex.Message}");
            return false;
        }
    }
    
    /// <summary>
    /// 生成配置管理器代码
    /// </summary>
    private string GenerateConfigManagerCode(List<TableData> tables)
    {
        var sb = new StringBuilder();
        
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("// 此文件由Excel转配置工具自动生成，请勿手动修改");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using UnityEngine;");
        sb.AppendLine();
        sb.AppendLine($"namespace {_config.CSharpNamespace};");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// 配置数据管理器");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public class ConfigManager : MonoBehaviour");
        sb.AppendLine("{");
        sb.AppendLine("    private static ConfigManager _instance;");
        sb.AppendLine("    public static ConfigManager Instance => _instance;");
        sb.AppendLine();
        
        // 生成各配置表的字典
        foreach (var table in tables)
        {
            sb.AppendLine($"    private Dictionary<int, {table.ClassName}> _{ToCamelCase(table.ClassName)}Dict = new();");
            sb.AppendLine($"    public IReadOnlyDictionary<int, {table.ClassName}> {table.ClassName}Dict => _{ToCamelCase(table.ClassName)}Dict;");
            sb.AppendLine();
        }
        
        sb.AppendLine("    private void Awake()");
        sb.AppendLine("    {");
        sb.AppendLine("        if (_instance == null)");
        sb.AppendLine("        {");
        sb.AppendLine("            _instance = this;");
        sb.AppendLine("            DontDestroyOnLoad(gameObject);");
        sb.AppendLine("        }");
        sb.AppendLine("        else");
        sb.AppendLine("        {");
        sb.AppendLine("            Destroy(gameObject);");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();
        
        // 生成加载方法
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// 加载所有配置");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public void LoadAllConfigs()");
        sb.AppendLine("    {");
        foreach (var table in tables)
        {
            sb.AppendLine($"        Load{table.ClassName}();");
        }
        sb.AppendLine("    }");
        sb.AppendLine();
        
        // 生成各配置表的加载方法
        foreach (var table in tables)
        {
            sb.AppendLine($"    private void Load{table.ClassName}()");
            sb.AppendLine("    {");
            sb.AppendLine($"        var json = Resources.Load<TextAsset>(\"Config/{table.ClassName}\");");
            sb.AppendLine("        if (json != null)");
            sb.AppendLine("        {");
            sb.AppendLine($"            var list = JsonUtility.FromJson<{table.ClassName}List>(json.text);");
            sb.AppendLine($"            foreach (var item in list.Items)");
            sb.AppendLine("            {");
            sb.AppendLine($"                _{ToCamelCase(table.ClassName)}Dict[item.Id] = item;");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine();
        }
        
        sb.AppendLine("}");
        sb.AppendLine();
        
        // 生成包装类（用于JSON反序列化）
        foreach (var table in tables)
        {
            sb.AppendLine($"[Serializable]");
            sb.AppendLine($"public class {table.ClassName}List");
            sb.AppendLine("{");
            sb.AppendLine($"    public List<{table.ClassName}> Items;");
            sb.AppendLine("}");
            sb.AppendLine();
        }
        
        return sb.ToString();
    }
    
    /// <summary>
    /// 转换为驼峰命名
    /// </summary>
    private string ToCamelCase(string name)
    {
        if (string.IsNullOrEmpty(name))
            return name;
        
        return char.ToLowerInvariant(name[0]) + name.Substring(1);
    }
}
