using ExcelToGame.Models;
using ExcelToGame.Utils;

namespace ExcelToGame.Core;

/// <summary>
/// 枚举管理模块 - 统一管理所有枚举定义
/// </summary>
public class EnumManager
{
    /// <summary>
    /// 枚举定义字典：枚举名 -> 枚举值集合
    /// </summary>
    private readonly Dictionary<string, HashSet<string>> _enumDefinitions = new();
    
    /// <summary>
    /// 枚举值来源：枚举名 -> (值 -> 来源表格)
    /// </summary>
    private readonly Dictionary<string, Dictionary<string, string>> _enumValueSources = new();
    
    /// <summary>
    /// 收集表格中的枚举值
    /// </summary>
    public void CollectEnums(TableData tableData)
    {
        var enumFields = tableData.GetEnumFields();
        
        foreach (var field in enumFields)
        {
            if (string.IsNullOrEmpty(field.EnumName)) continue;
            
            if (!_enumDefinitions.ContainsKey(field.EnumName))
            {
                _enumDefinitions[field.EnumName] = new HashSet<string>();
                _enumValueSources[field.EnumName] = new Dictionary<string, string>();
            }
            
            // 收集该字段的所有枚举值
            foreach (var row in tableData.GetExportableRows())
            {
                var value = row.GetValue(field.Name);
                if (value == null) continue;
                
                if (field.IsArray && value is List<object?> arrayValues)
                {
                    foreach (var item in arrayValues)
                    {
                        if (item != null)
                        {
                            var strValue = item.ToString()!;
                            _enumDefinitions[field.EnumName].Add(strValue);
                            _enumValueSources[field.EnumName][strValue] = tableData.FileName;
                        }
                    }
                }
                else
                {
                    var strValue = value.ToString()!;
                    _enumDefinitions[field.EnumName].Add(strValue);
                    _enumValueSources[field.EnumName][strValue] = tableData.FileName;
                }
            }
        }
        
        Logger.Table(tableData.FileName, $"收集到 {enumFields.Count} 个枚举字段");
    }
    
    /// <summary>
    /// 获取所有枚举定义
    /// </summary>
    public IReadOnlyDictionary<string, HashSet<string>> GetAllEnums()
    {
        return _enumDefinitions;
    }
    
    /// <summary>
    /// 获取指定枚举的所有值
    /// </summary>
    public HashSet<string>? GetEnumValues(string enumName)
    {
        return _enumDefinitions.TryGetValue(enumName, out var values) ? values : null;
    }
    
    /// <summary>
    /// 检查枚举值是否合法
    /// </summary>
    public bool IsValidEnumValue(string enumName, string value)
    {
        if (_enumDefinitions.TryGetValue(enumName, out var values))
        {
            return values.Contains(value);
        }
        return false;
    }
    
    /// <summary>
    /// 验证表格中的枚举值
    /// </summary>
    public void ValidateTableEnums(TableData tableData)
    {
        var enumFields = tableData.GetEnumFields();
        
        foreach (var field in enumFields)
        {
            if (string.IsNullOrEmpty(field.EnumName)) continue;
            
            if (!_enumDefinitions.TryGetValue(field.EnumName, out var validValues))
            {
                tableData.AddWarning($"枚举 '{field.EnumName}' 未定义任何值");
                continue;
            }
            
            foreach (var row in tableData.GetExportableRows())
            {
                var value = row.GetValue(field.Name);
                if (value == null) continue;
                
                if (field.IsArray && value is List<object?> arrayValues)
                {
                    foreach (var item in arrayValues)
                    {
                        if (item != null && !validValues.Contains(item.ToString()!))
                        {
                            tableData.AddError($"第 {row.RowNumber} 行，字段 '{field.Name}' 的枚举值 '{item}' 不合法");
                        }
                    }
                }
                else
                {
                    if (!validValues.Contains(value.ToString()!))
                    {
                        tableData.AddError($"第 {row.RowNumber} 行，字段 '{field.Name}' 的枚举值 '{value}' 不合法");
                    }
                }
            }
        }
    }
    
    /// <summary>
    /// 生成C#枚举代码
    /// </summary>
    public string GenerateCSharpEnums(string namespaceName)
    {
        var sb = new System.Text.StringBuilder();
        
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("// 此文件由Excel转配置工具自动生成，请勿手动修改");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine();
        sb.AppendLine($"namespace {namespaceName};");
        sb.AppendLine();
        
        foreach (var (enumName, values) in _enumDefinitions.OrderBy(e => e.Key))
        {
            if (values.Count == 0) continue;
            
            sb.AppendLine("/// <summary>");
            sb.AppendLine($"/// {enumName} 枚举");
            sb.AppendLine("/// </summary>");
            sb.AppendLine($"public enum {enumName}");
            sb.AppendLine("{");
            
            var sortedValues = values.OrderBy(v => v).ToList();
            for (int i = 0; i < sortedValues.Count; i++)
            {
                var value = sortedValues[i];
                var enumValueName = ToValidEnumMemberName(value);
                sb.AppendLine($"    {enumValueName} = {i},");
            }
            
            sb.AppendLine("}");
            sb.AppendLine();
        }
        
        return sb.ToString();
    }
    
    /// <summary>
    /// 生成TypeScript枚举代码
    /// </summary>
    public string GenerateTypeScriptEnums()
    {
        var sb = new System.Text.StringBuilder();
        
        sb.AppendLine("/**");
        sb.AppendLine(" * 此文件由Excel转配置工具自动生成，请勿手动修改");
        sb.AppendLine(" */");
        sb.AppendLine();
        
        foreach (var (enumName, values) in _enumDefinitions.OrderBy(e => e.Key))
        {
            if (values.Count == 0) continue;
            
            sb.AppendLine("/**");
            sb.AppendLine($" * {enumName} 枚举");
            sb.AppendLine(" */");
            sb.AppendLine($"export enum {enumName}");
            sb.AppendLine("{");
            
            var sortedValues = values.OrderBy(v => v).ToList();
            for (int i = 0; i < sortedValues.Count; i++)
            {
                var value = sortedValues[i];
                var enumValueName = ToValidEnumMemberName(value);
                sb.AppendLine($"    {enumValueName} = {i},");
            }
            
            sb.AppendLine("}");
            sb.AppendLine();
        }
        
        return sb.ToString();
    }
    
    /// <summary>
    /// 将字符串转换为合法的枚举成员名
    /// </summary>
    private string ToValidEnumMemberName(string value)
    {
        // 移除非法字符，确保是合法的C#/TS标识符
        var result = new System.Text.StringBuilder();
        
        for (int i = 0; i < value.Length; i++)
        {
            char c = value[i];
            if (i == 0)
            {
                // 首字符必须是字母或下划线
                if (char.IsLetter(c) || c == '_')
                {
                    result.Append(c);
                }
                else if (char.IsDigit(c))
                {
                    result.Append('_');
                    result.Append(c);
                }
                else
                {
                    result.Append('_');
                }
            }
            else
            {
                // 后续字符可以是字母、数字或下划线
                if (char.IsLetterOrDigit(c) || c == '_')
                {
                    result.Append(c);
                }
                else
                {
                    result.Append('_');
                }
            }
        }
        
        var name = result.ToString();
        
        // 如果为空或与保留字冲突，添加前缀
        if (string.IsNullOrEmpty(name) || IsCSharpKeyword(name))
        {
            name = "_" + name;
        }
        
        return name;
    }
    
    /// <summary>
    /// 检查是否为C#关键字
    /// </summary>
    private bool IsCSharpKeyword(string word)
    {
        var keywords = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
        {
            "abstract", "as", "base", "bool", "break", "byte", "case", "catch", "char", "checked",
            "class", "const", "continue", "decimal", "default", "delegate", "do", "double", "else",
            "enum", "event", "explicit", "extern", "false", "finally", "fixed", "float", "for",
            "foreach", "goto", "if", "implicit", "in", "int", "interface", "internal", "is",
            "lock", "long", "namespace", "new", "null", "object", "operator", "out", "override",
            "params", "private", "protected", "public", "readonly", "ref", "return", "sbyte",
            "sealed", "short", "sizeof", "stackalloc", "static", "string", "struct", "switch",
            "this", "throw", "true", "try", "typeof", "uint", "ulong", "unchecked", "unsafe",
            "ushort", "using", "virtual", "void", "volatile", "while"
        };
        
        return keywords.Contains(word);
    }
}
